In [1]:
from numpy import asarray
data=[[1,2,3],[4,5,6]]
data=asarray(data)
print("Numpy array")
print(data)
print("_____________________________")
totalr=data.sum(axis=1)
totalc=data.sum(axis=0)
print("Row Sum")
print(totalr)
print("Column Sum")
print(totalc)
print("_____________________________")
meanr=data.mean(axis=1)
meanc=data.mean(axis=0)
print("Row Mean")
print(meanr)
print("Column Mean")
print(meanc)
print("_____________________________")
stdr=data.std(axis=1)
stdc=data.std(axis=0)
print("Row STD")
print(stdr)
print("Column STD")
print(stdc)

Numpy array
[[1 2 3]
 [4 5 6]]
_____________________________
Row Sum
[ 6 15]
Column Sum
[5 7 9]
_____________________________
Row Mean
[2. 5.]
Column Mean
[2.5 3.5 4.5]
_____________________________
Row STD
[0.81649658 0.81649658]
Column STD
[1.5 1.5 1.5]
